$(function(){
	$('#myForm').ajaxForm({
		beforeSend:function(){
			var verdict= validate();
			if(!verdict){
				return false;
			}else{
				$(".progress").show();
			}
		},
		uploadProgress:function(event,position,total,percentComplete){
			$(".progress-bar").width(percentComplete+'%');
			$(".sr-only").html(percentComplete+'%');
		},
		success:function(){
			$(".progress").hide();
		},
		complete:function(response){
			if(response.responseText=="success"){
				$(".progress").hide();
				$("#name").val("");
				$("#price").val("");
				$("#desc").val("");
				$("#stock").val("");
				$("#successAlert").show().delay(1000).fadeOut();
			}else{
				displayProductError(response.responseText);
			}
		}
	});
	$("#successAlert").hide();
	$("#errorAlert").hide();
	$(".progress").hide();
});